services:
  app:
    build: .
    container_name: unproyecto_app
    restart: always
    ports:
      - "3001:3001"
    # Aquí le decimos a Docker que lea los valores desde el archivo .env del servidor
    env_file:
      - .env
    environment:
      - NODE_ENV=production